---
title: "Homework 5_draft_CS"
author: "Christian Sewor"
date: "2022-12-01"
output: html_document
---

```{r setup, echo = TRUE, messages = FALSE, warning = FALSE}
## Packages Used
library(knitr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(scales)
library(lubridate)
library(zoo)
```


```{r Reading_Data, echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE}
## Reading data

homicide <- read.csv("~/MEGAsync/Training2021/R_Class_CSU/Homework-5/Data/homicide-data.csv")
head (homicide, n=5)
```

```{r Reading_Data, echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE}

## Creating a new Column - city_name
homicide_baltimore <- homicide %>% 
  mutate (city_name = paste(city, state, sep = ", ")) %>% 
  filter(city == "Baltimore") %>% ## Filtering data to only include cases in Baltimore
  mutate(reported_date = ymd(reported_date),
         month_year = format_ISO8601(reported_date, precision = "ym")) %>% ##Reassigning column as date class and extracting month and year details into a new column
  group_by(month_year) %>% ## Creating a data frame which includes month and year details and case counts 
  count() %>% 
  rename (total_cases = n) 

homicide_baltimore$month_year <- as.Date(as.yearmon(homicide_baltimore$month_year), frac = 1) ## Reassigning newly created month year column as a date class

## Extracting only month details from  month-year column and creating a new variable for season
homicide_baltimore<-homicide_baltimore %>% 
  mutate(actual_month = month(month_year),
         season = actual_month %in% c (5:9)) 

## Renaming TRUE and FALSE logical vector to Summer and Winter
homicide_baltimore$season[homicide_baltimore$season == "TRUE"] <- "Summer"
homicide_baltimore$season[homicide_baltimore$season == "FALSE"] <- "Winter"

head(homicide_baltimore, n =5 )
```



```{r Generating Plot, echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, fig.width = 8,fig.height= 2.5}

homicide_baltimore %>% 
  ggplot(aes(x = month_year))+
  geom_bar(aes(weight = total_cases, fill = season), color = "black")+
             scale_fill_manual(values= c("Summer" = "grey", "Winter" = "cadetblue3"))+
  geom_smooth(aes(y = total_cases), se = FALSE, span = 0.1, lwd = 2.0) +
  scale_x_date(date_labels = "%Y")+
  geom_vline(xintercept = as.numeric(as.Date("2015-04-15")), 
              color = "red", linetype= "dashed", 
              lwd = 2.0)+
  annotate("text", x= as.Date("2015-04-15"), y= 45, label="Arrest of Freddie Gray", color= "azure3", hjust= 1)+
  labs(x = "Date", 
       y = "Monthly homicides" )+
  ggtitle(label= "Homicides in Baltimore, MD")+
  theme_dark()+
  theme(legend.position = "bottom", legend.title=element_blank())
  
```